# Generated by Django 3.0 on 2022-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [migrations.RunSQL("""
                   INSERT INTO profiles_profile (
                       favorite_city,
                       user_id
                   )
                   SELECT
                       favorite_city,
                       user_id
                   FROM
                       oc_lettings_site_profile;
               """, reverse_sql="""
                   INSERT INTO oc_lettings_site_profile (
                       favorite_city,
                       user_id
                   )
                   SELECT
                       favorite_city,
                       user_id
                   FROM
                       profiles_profile;
               """)
                  ]
