version: 2.1

orbs:
  python: circleci/python@2.0.3
  github-super-linter: circleci/github-super-linter@1.0.1
  docker: circleci/docker@2.0.3
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    docker:
      - image: cimg/python:3.10.4
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  build-push:
    docker:
      - image: cimg/python:3.10.4
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - heroku/check-authentication
      - docker/install-docker
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/${HEROKU_APP_NAME}
          tag: $CIRCLE_SHA1,latest
          extra_build_args: --build-arg SECRET_KEY=${SECRET_KEY} --build-arg ALLOWED_HOSTS=${ALLOWED_HOSTS} --build-arg DEBUG=${DEBUG}
      - docker/push:
          image: ${DOCKER_LOGIN}/${HEROKU_APP_NAME}
          tag: $CIRCLE_SHA1,latest
  pull-and-deploy:
    docker:
      - image: cimg/python:3.10.4
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - docker/install-docker
      - docker/pull:
          images: ${DOCKER_LOGIN}/${HEROKU_APP_NAME}:${CIRCLE_SHA1}
      - run : heroku container:login
      - run: docker tag ${DOCKER_LOGIN}/${HEROKU_APP_NAME}:${CIRCLE_SHA1} registry.heroku.com/${HEROKU_APP_NAME}/web
      - run: docker push registry.heroku.com/${HEROKU_APP_NAME}/web
      - heroku/release-docker-image:
          process-types: web 
          api-key: HEROKU_API_KEY
workflows:
  test-lint-build-deploy:
    jobs:
      - github-super-linter/lint
      - test:
          requires:
            - github-super-linter/lint
      - build-push:
          requires:
            - test
      - pull-and-deploy:
          requires:
            - build-push
      
