version: 2.1

orbs:
  python: circleci/python@2.0.3
  github-super-linter: circleci/github-super-linter@1.0.1
  docker: circleci/docker@2.0.3
  heroku: circleci/heroku@1.2.6
jobs:
  build-push:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - docker/install-docker
      - docker/check:
          docker-username: DOCKER_LOGIN 
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: alaet/oc-lettings-om
          tag: $CIRCLE_SHA1,latest
      - docker/push:
          image: alaet/oc-lettings-om
          tag: $CIRCLE_SHA1,latest
  pull-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - heroku/install
      - docker/install-docker
      - docker/pull:
          images: alaet/oc-lettings-om:latest
      - heroku/push-docker-image:
          process-types: web 
          api-key: HEROKU_API_KEY
      - heroku/release-docker-image:
          process-types: web 
          api-key: HEROKU_API_KEY
workflows:
  test-lint-build-deploy:
    jobs:
      - build-push
      - pull-and-test:
          requires:
            - build-push
      # - github-super-linter/lint
