version: 2.1

orbs:
  python: circleci/python@2.0.3
  github-super-linter: circleci/github-super-linter@1.0.1
  docker: circleci/docker@2.0.3
  heroku: circleci/heroku@1.2.6
jobs:
  push-docker-image:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - heroku/push-docker-image:
         api-key: HEROKU_API_KEY
         recursive: true
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - heroku/install
      - docker/install-docker-tools
      - docker/check:
          docker-username: DOCKER_LOGIN 
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: alaet/testimg
          tag: $CIRCLE_SHA1,latest
      - docker/push:
          image: alaet/testimg
          tag: $CIRCLE_SHA1,latest
      - docker/pull:
          images: alaet/testimg
      - heroku/push-docker-image:
         api-key: HEROKU_API_KEY
workflows:
  test-lint-build-deploy:
    jobs:
      - build-and-test
      - github-super-linter/lint
