# Generated by Django 3.0 on 2022-04-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220411_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
